### ISSUE TITLE
Some signal processing confused me , please help

### ISSUE THREAD

**Issue by youngsuenXMLY** [Js-Mim/mss_pytorch#8]
In helpers/nnet_helpers.py, line 144:  vs_train *= 2.
This vs_train is doubled after IRM apply. This really confused me. Would you please give some interpretation about this processing?

**Comment by youngsuenXMLY** [comment]
Additional one question, in helpers/nnet_helpers.py,  line 145 and line 146
vs_train = np.clip(vs_train, a_min=0., a_max=1.)
ms_train = np.clip(ms_train, a_min=0., a_max=1.)
vs_train is the IRM-filtered output magnitude and ms_train is the mixture magnitude in frequency domain,  the magnitude of vs_train or magnitude may be larger than 1. in some frequency bins. Why 
is the magnitude clipped to 1.0? Is there any normalization process before this step?

**Comment by Js-Mim** [comment]
Hi @youngsuenXMLY,

IRM is applied to alleviate the problem of the mixing process of the stems/tracks from the MedleydB dataset.
It was later observed that some of the vocal tracks (again from the same subset of MedleydB, which were served as target functions "vs_train") were lacking energy. Since the data normalization is outside the scope of our work (at least for the moment), during training it was also observed that for these tracks the "Masker" of our proposed model was learning something more trivial than expected. A small scaling factor seemed to "push" the model into the correct "direction". Please note, that since the new dataset (musdb: https://sigsep.github.io/ ) uses re-mixed MedleydB tracks, this process can be neglected.

As far it concerns the clipping to a maximum value of one, some coefficients of magnitude spectra might exceed the value of one, causing minor trouble during optimization of the recurrent neural networks (GRUs) with skip-connections, due to the tanh non-linearity. However, please note that this clipping does **not** affect the audio signals perceptually, and is **not** used during testing.

Hope this clarifies things.
