### ISSUE TITLE
Singing voice

### ISSUE THREAD

**Issue by zhly0** [Js-Mim/mss_pytorch#9]
Hi，thanks for your nice work，this is not a issue，but a question：how can I judge a wav file，is it a man singing or a man speaking？is your code could done this？Thanks！

**Comment by Js-Mim** [comment]
Hi and thanks for your interest. That's a very nice and tricky question :) . That relies quite much on the training data you are going to use. For instance, in the current state of the model it is not very clear how the model behaves on speech or singing, because the used dataset sometimes has some sampled singing voice or speech into the "other" music source category which we try to remove. The best way would be to try it out, and if possible fine tune it for speech on top of music.

**Comment by zhly0** [comment]
Thanks！
